{% set python_min = '3.10' %}
{% set name = "pycoast" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 301d8fcf38805f23ddbcbfbf2e9bd6c466aaee92553ffceccee0f2b7ad7e3637

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer-518
  run:
    - python >={{ python_min }}
    - pyshp
    - numpy
    - pyproj
    - pillow
    - aggdraw

test:
  requires:
    - python {{ python_min }}
  imports:
    - pycoast
    - pycoast.tests

about:
  home: https://github.com/pytroll/pycoast
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Writing of coastlines, borders and rivers to images in Python
  description: Writing of coastlines, borders and rivers to images in Python
  doc_url: http://pycoast.readthedocs.io
  dev_url: https://github.com/pytroll/pycoast

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
