{% set name = "pycoast" %}
{% set version = "1.3.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e3ad9a8580382d3e89787471cd000a83098c1bd41fce584c959655c5f67ed9b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyshp
    - numpy
    - pyproj
    - pillow
    - six
    - aggdraw

test:
  imports:
    - pycoast
    - pycoast.tests

about:
  home: https://github.com/pytroll/pycoast
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Writing of coastlines, borders and rivers to images in Python
  description: Writing of coastlines, borders and rivers to images in Python
  doc_url: http://pycoast.readthedocs.io
  dev_url: https://github.com/pytroll/pycoast

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
