{% set name = "pycoast" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aabca0e80385ddf37e8bdea8258252ec6b4462b2f2baec135599ea193834402d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - versioneer-518
  run:
    - python >=3.8
    - pyshp
    - numpy
    - pyproj
    - pillow
    - aggdraw

test:
  imports:
    - pycoast
    - pycoast.tests

about:
  home: https://github.com/pytroll/pycoast
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Writing of coastlines, borders and rivers to images in Python
  description: Writing of coastlines, borders and rivers to images in Python
  doc_url: http://pycoast.readthedocs.io
  dev_url: https://github.com/pytroll/pycoast

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
