{% set name = "pycoast" %}
{% set version = "1.2.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "68f0f595a69fa03f9908c6de2087babcb78636e60d15b28cf75300418a1f43d3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyshp
    - numpy
    - pyproj
    - pillow
    - six
    - aggdraw

test:
  imports:
    - pycoast
    - pycoast.tests

about:
  home: https://github.com/pytroll/pycoast
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Writing of coastlines, borders and rivers to images in Python
  description: Writing of coastlines, borders and rivers to images in Python
  doc_url: http://pycoast.readthedocs.io
  dev_url: https://github.com/pytroll/pycoast

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
