travis:
  secure:
    BINSTAR_TOKEN: S9PQe4CgwC9jL6CIhjGMUKQBCvJWuHd7ssOC4B8ADqrwjeSLPj3WVxwxRMuc+H3mlPNFtNp+d3Qj0QUy7zoU5UQPja93YJtn/P0GP4WoeqzJa1RMB/2PL9YLQAj7UXhf+Myru8TopTR9btiFEt2yb2l92oLRjHhoRrg1kHU/PzBM65WUJsxESAEBYvg+XNIjIR6elOpCvTiJJrpRj/hF4kOqCw5amN1ngb+25s3AJzW7KTvalXPtUWjCEArBrfWOxM2fognQGj3LrDS2Taqtho0I4vp0NGhtABOn8jsRgY9yQsVGeNf7E/jzYgp8tvKUgZg56cJIRgiOyWyhQUWIBCajCvoeeebljcAouQoMK7KDEi/weByiiuU1ptNvNYTsfOtLZYXccUDIOFHldibu/5fAf1nBEjngFGyf8ZJMqajA/X4p+YQxo4ZNaQYcgBA8RUiMDQc7h2c9OKCbumxd8hG8kUYN/zPBaF4q6sC29Gb3wH9m3cllV4W8FqaXC2EV+DysHtcZ9ZKADSF43EOf0bMpiLke5SdzG35/iITwSLx5aOhg+ltRykjJtHTQn5CmfQMs7wxNVUyjVnghx7Qkdt6jSLHU/qw7Dt60meDoIH+oMiLpWFBFyxMlcmCpJqpgfK0tmm1rZWsFRM0DfVLqloxvHhroPQFtfXdEN1YTOXs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
