travis:
  secure:
    BINSTAR_TOKEN: Icobab0j9PIvNn1sso+PSAYUtRViP4NN/RlO2lbDE15+VqjY5JKlq+dMloetl4Mdkj76qyk6qXTeZ4nGWgPq9PpVyKd/3CdOImqj/DY3fwZoWrYUy1A0567GEodJmI4wjbRT1ClMxdRDYgTyUxEvdTCVYESa74R14ZXrAt2KYs5pi02T9/+FQhGK8V4na2rUrzV1VczEvq5RXacYrkHXiJqkxRJUw6ofjADmi59xODw7eGUct7xxyqUtHa9jowilWPiOPybIgzQU0h/JcVsSl+XmHsN/Ks0mDC95rVMA5DuJ7zsOAW3UO6Yzqx8S0vmFePag+4kW6N1v9TCCZuzgdukPTMbj+d0dPBhbdPz2tgC2H4FX7+IJOe5En5dmKD36PKEmTaJeBUE5nAuFX2GV990dbvBBIf9h7LGrPO3lkHi4QblpmbGxI8vobGrcxwckCqN61TlY3K+vG4/b5/zT6YenPfEHTktv0/S2aca3UN/smoZ9xAY11/XVK5AXtRyQnVTONHV8sTmGpXAI2m23IgB+uhRzm9lgTFryNgGXNJ3LL4cByf270zYYhBW3GCDg7YtCz/BxnuEadnVsQ4Xz7Mct9sUzLeyHPU06lW7lmcJtXN93u/s4QkdMY3ALGlit61Qz0Vw+kI8vnmHmhWzrRHGn7U0R90MqfU5kQPtXQqA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
